#define DEFAULT_VOLUME 15 
#define DEFAULT_IMPEDANCE 10 
#define DEFAULT_CALIB_STEPS 48
#define DEFAULT_BALANCE_VALUE_DB 1 
#define DEFAULT_TEMPERATURE 25 


typedef enum { LEFTCHAN, RIGHTCHAN } BalanceChan;
