#! /bin/sh
#
# This is an init script for Debian Sid
# Copy it to /etc/init.d/ldrattnapp 
#


test -f /usr/local/sbin/ldrattnapp || exit 0

case "$1" in
  start)
    echo -n "Starting ldrattnapp  daemon: ldrattnapp"
    start-stop-daemon --start --background -m --quiet --pidfile /var/run/ldrattnapp.pid --exec /usr/local/sbin/ldrattnapp  
    start-stop-daemon --start --background --quiet --exec /usr/bin/python /var/www/ldrattn/app.py 
    echo "."
    ;;
  stop)
    echo -n "Stopping ldrattnapp daemon: ldrattnapp"
    /usr/local/sbin/client -M 	
    start-stop-daemon --stop --quiet --pidfile /var/run/ldrattnapp.pid --exec /usr/local/sbin/ldrattnapp
    start-stop-daemon --stop --quiet --exec /usr/bin/python /var/www/ldrattn/app.py 
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --pidfile /var/run/ldrattnapp.pid  --signal 1 --exec /usr/local/sbin/ldrattnapp
    ;;
  restart)
    echo -n "Stopping ldrattnapp daemon: ldrattnapp"
    /usr/local/sbin/client -M 	
    start-stop-daemon --stop --quiet --pidfile /var/run/ldrattnapp.pid --exec /usr/local/sbin/ldrattnapp
    start-stop-daemon --stop --quiet --exec /usr/bin/python /var/www/ldrattn/app.py 
    sleep 1
    echo -n "Starting ldrattnapp daemon: ldrattnapp"
    start-stop-daemon --start --background -m --quiet --pidfile /var/run/ldrattnapp.pid --exec /usr/local/sbin/ldrattnapp
    start-stop-daemon --start --background --quiet --exec /usr/bin/python /var/www/ldrattn/app.py 
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/ldrattnapp {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
